spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?charcaterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 1q2w3e4r

  jpa:
    generate-ddl: true

server:
  port: 8082